[project]
name = "aiviz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "manim>=0.19.0",
    "pip>=25.0.1",
]
